# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(600, 700)
        Menu.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(240, 350, 121, 41))
        self.play.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.play.setObjectName("play")
        self.buttonGroup = QtWidgets.QButtonGroup(Menu)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.play)
        self.leaders = QtWidgets.QPushButton(self.centralwidget)
        self.leaders.setGeometry(QtCore.QRect(240, 400, 121, 41))
        self.leaders.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.leaders.setObjectName("leaders")
        self.buttonGroup.addButton(self.leaders)
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(240, 450, 121, 41))
        self.setting.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.setting.setObjectName("setting")
        self.buttonGroup.addButton(self.setting)
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(240, 500, 121, 41))
        self.quit.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.quit.setObjectName("quit")
        self.buttonGroup.addButton(self.quit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 130, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(170, 85, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_up1 = QtWidgets.QLabel(self.centralwidget)
        self.label_up1.setGeometry(QtCore.QRect(10, 10, 581, 111))
        self.label_up1.setText("")
        self.label_up1.setObjectName("label_up1")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(570, 10, 16, 16))
        self.button_exit.setStyleSheet("border-radius: 7px;\n"
"background-color: rgb(231, 76, 60);")
        self.button_exit.setText("")
        self.button_exit.setObjectName("button_exit")
        Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "MainWindow"))
        self.play.setText(_translate("Menu", "Играть"))
        self.leaders.setText(_translate("Menu", "Таблица лидеров"))
        self.setting.setText(_translate("Menu", "Настройки"))
        self.quit.setText(_translate("Menu", "Выход"))
        self.label.setText(_translate("Menu", "Tetris"))
