# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'management_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Management(object):
    def setupUi(self, Management):
        Management.setObjectName("Management")
        Management.resize(391, 300)
        Management.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(Management)
        self.centralwidget.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget.setObjectName("centralwidget")
        self.label_up = QtWidgets.QLabel(self.centralwidget)
        self.label_up.setGeometry(QtCore.QRect(10, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_up.setFont(font)
        self.label_up.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_up.setAlignment(QtCore.Qt.AlignCenter)
        self.label_up.setObjectName("label_up")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(360, 10, 16, 16))
        self.button_exit.setStyleSheet("border-radius: 7px;\n"
"background-color: rgb(231, 76, 60);")
        self.button_exit.setText("")
        self.button_exit.setObjectName("button_exit")
        self.key_pause = QtWidgets.QLabel(self.centralwidget)
        self.key_pause.setGeometry(QtCore.QRect(120, 60, 47, 44))
        self.key_pause.setText("")
        self.key_pause.setObjectName("key_pause")
        self.key_up = QtWidgets.QLabel(self.centralwidget)
        self.key_up.setGeometry(QtCore.QRect(80, 140, 47, 44))
        self.key_up.setText("")
        self.key_up.setObjectName("key_up")
        self.key_left = QtWidgets.QLabel(self.centralwidget)
        self.key_left.setGeometry(QtCore.QRect(20, 200, 47, 44))
        self.key_left.setText("")
        self.key_left.setObjectName("key_left")
        self.key_down = QtWidgets.QLabel(self.centralwidget)
        self.key_down.setGeometry(QtCore.QRect(80, 200, 47, 44))
        self.key_down.setText("")
        self.key_down.setObjectName("key_down")
        self.key_right = QtWidgets.QLabel(self.centralwidget)
        self.key_right.setGeometry(QtCore.QRect(140, 200, 47, 44))
        self.key_right.setText("")
        self.key_right.setObjectName("key_right")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(170, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        Management.setCentralWidget(self.centralwidget)

        self.retranslateUi(Management)
        QtCore.QMetaObject.connectSlotsByName(Management)

    def retranslateUi(self, Management):
        _translate = QtCore.QCoreApplication.translate
        Management.setWindowTitle(_translate("Management", "MainWindow"))
        self.label_up.setText(_translate("Management", "Management"))
        self.label_1.setText(_translate("Management", "- pause the game"))
        self.label_2.setText(_translate("Management", "- rotate plate"))
        self.label_3.setText(_translate("Management", "- move plate left/down/right"))
