# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(601, 700)
        Settings.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_up1 = QtWidgets.QLabel(self.centralwidget)
        self.label_up1.setGeometry(QtCore.QRect(10, 10, 581, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(24)
        self.label_up1.setFont(font)
        self.label_up1.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_up1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_up1.setObjectName("label_up1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 200, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 85, 255);")
        self.label.setObjectName("label")
        self.volume_slider_game = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider_game.setGeometry(QtCore.QRect(320, 200, 221, 22))
        self.volume_slider_game.setMaximum(100)
        self.volume_slider_game.setProperty("value", 10)
        self.volume_slider_game.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider_game.setObjectName("volume_slider_game")
        self.save_setting = QtWidgets.QPushButton(self.centralwidget)
        self.save_setting.setGeometry(QtCore.QRect(220, 400, 161, 41))
        self.save_setting.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.save_setting.setObjectName("save_setting")
        self.delete_account = QtWidgets.QPushButton(self.centralwidget)
        self.delete_account.setGeometry(QtCore.QRect(220, 520, 161, 41))
        self.delete_account.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.delete_account.setObjectName("delete_account")
        self.back_ = QtWidgets.QPushButton(self.centralwidget)
        self.back_.setGeometry(QtCore.QRect(430, 610, 121, 41))
        self.back_.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.back_.setObjectName("back_")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 85, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.volume_slider_main = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider_main.setGeometry(QtCore.QRect(320, 340, 221, 22))
        self.volume_slider_main.setMaximum(100)
        self.volume_slider_main.setProperty("value", 10)
        self.volume_slider_main.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider_main.setObjectName("volume_slider_main")
        self.choice_music_game = QtWidgets.QPushButton(self.centralwidget)
        self.choice_music_game.setGeometry(QtCore.QRect(160, 120, 271, 41))
        self.choice_music_game.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.choice_music_game.setObjectName("choice_music_game")
        self.choice_music_main = QtWidgets.QPushButton(self.centralwidget)
        self.choice_music_main.setGeometry(QtCore.QRect(160, 260, 271, 41))
        self.choice_music_main.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.choice_music_main.setObjectName("choice_music_main")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(570, 10, 16, 16))
        self.button_exit.setStyleSheet("border-radius: 7px;\n"
"background-color: rgb(231, 76, 60);")
        self.button_exit.setText("")
        self.button_exit.setObjectName("button_exit")
        self.reset_best_score = QtWidgets.QPushButton(self.centralwidget)
        self.reset_best_score.setGeometry(QtCore.QRect(220, 460, 161, 41))
        self.reset_best_score.setStyleSheet("background-color: #22222e;\n"
"border: 20px sold #f66867;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;\n"
"")
        self.reset_best_score.setObjectName("reset_best_score")
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "MainWindow"))
        self.label_up1.setText(_translate("Settings", "Настройки"))
        self.label.setText(_translate("Settings", "Громкость музыки в игре"))
        self.save_setting.setText(_translate("Settings", "Сохранить настройки"))
        self.delete_account.setText(_translate("Settings", "Удалить аккаунт"))
        self.back_.setText(_translate("Settings", "Назад"))
        self.label_2.setText(_translate("Settings", "Громкость музыки в главном меню"))
        self.choice_music_game.setText(_translate("Settings", "Выбрать свою музыку в игре(.MP3)"))
        self.choice_music_main.setText(_translate("Settings", "Выбрать свою музыку главного меню(.MP3)"))
        self.reset_best_score.setText(_translate("Settings", "Сбросить рекорд"))
